// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmhm2h4sdAHgPq6vjSfgmcV45TwsI7I4o',
    appId: '1:723723390327:web:172f7a3db264c0b620e572',
    messagingSenderId: '723723390327',
    projectId: 'prect-2fc33',
    authDomain: 'prect-2fc33.firebaseapp.com',
    storageBucket: 'prect-2fc33.appspot.com',
    measurementId: 'G-1FWZWJ1F6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIgv22d58XFhJnJ9Qhb1SfkfoaHPa_I78',
    appId: '1:723723390327:android:a6ab55237e56353620e572',
    messagingSenderId: '723723390327',
    projectId: 'prect-2fc33',
    storageBucket: 'prect-2fc33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUEnZmn5LEl2OxXMdXsKGyu3x4aeIQbMA',
    appId: '1:723723390327:ios:6842d05e0a49fcb020e572',
    messagingSenderId: '723723390327',
    projectId: 'prect-2fc33',
    storageBucket: 'prect-2fc33.appspot.com',
    iosClientId:
        '723723390327-b3ffncfl1irtjk1cb3tguo0g9ii74c5o.apps.googleusercontent.com',
    iosBundleId: 'com.iruma.prect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUEnZmn5LEl2OxXMdXsKGyu3x4aeIQbMA',
    appId: '1:723723390327:ios:6842d05e0a49fcb020e572',
    messagingSenderId: '723723390327',
    projectId: 'prect-2fc33',
    storageBucket: 'prect-2fc33.appspot.com',
    iosClientId:
        '723723390327-b3ffncfl1irtjk1cb3tguo0g9ii74c5o.apps.googleusercontent.com',
    iosBundleId: 'com.iruma.prect',
  );
}
